name: Rust

on:
  push: 
    paths: 
      - 'wasm/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      working-directory: ./wasm
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./wasm
